export const PROFILE_INFO = 'PROFILE_INFO';
export type PROFILE_INFO = typeof PROFILE_INFO;

export const USERS_LIST = 'USERS_LIST';
export type USERS_LIST = typeof USERS_LIST;

export const TOGGLE_LOCATIONS = 'TOGGLE_LOCATIONS';
export type TOGGLE_LOCATIONS = typeof TOGGLE_LOCATIONS;

export const SELECT_VENUE_IMAGE = 'SELECT_VENUE_IMAGE';
export type SELECT_VENUE_IMAGE = typeof SELECT_VENUE_IMAGE;

export const SELECT_VENUE_DETAILS_TAB = 'SELECT_VENUE_DETAILS_TAB';
export type SELECT_VENUE_DETAILS_TAB = typeof SELECT_VENUE_DETAILS_TAB;

export const VENUE_FILTER = 'VENUE_FILTER';
export type VENUE_FILTER = typeof VENUE_FILTER;

export const LOAD_VENUE_DETAILS = 'LOAD_VENUE_DETAILS';
export type LOAD_VENUE_DETAILS = typeof LOAD_VENUE_DETAILS;

export const LOAD_VENUES_LIST = 'LOAD_VENUES_LIST';
export type LOAD_VENUES_LIST = typeof LOAD_VENUES_LIST;
